### ISSUE TITLE
Construction API Testing 2.0

### ISSUE THREAD

**Issue by patrick-ogrady** [coinbase/rosetta-cli#112]
Replaces #86
Closes #119 

### Motivation
The recently added Construction API testing (#81) does not support multi-currency sends, on-chain address generation, testing non-transfer transactions, or testing account/utxo transfers on the same network. This makes it impossible to test the Construction API of many projects implementing the Rosetta API.

### Solution
We need to redesign the `constructor` to allow for the generic execution of a core set of primitives (`generate_key`, `save_address`, `derive`, `set_variable`, `find_account`, `find_coin`, `print_message`, `wait_for_funds`, `math`, `random_string`) that can be stitched together into scripts (with some shared state). These "scripts" should be called `scenarios` and it should be possible to combine multiple `scenarios` together into a `workflow` where all execution state is shared. At the end of each `scenario` execution it should be possible to execute a transaction which will allow multiple transactions to be broadcasted as part of a `workflow`. The `constructor` will manage the execution of these `workflows` (instantiated as `jobs`) using a new storage backend called `JobStorage`.

#### Preview
```text
Workflow
  []Scenario
    []Action

Job (instance of a plan)
  Identifier
  State
  Index
  []Scenario
  Status [ready, broadcasting, failed, complete]

  Create(Plan) Job
  Intent() [run after execute] -> sets status to broadcasting

Worker (executes job)
  Helper (fetcher, balanceStorage, coinStorage, broadcastStorage, keyStorage)
    Derive
    LockedAddresses
    AccountBalance
    CoinBalance
    StoreAddress

  processScenario(State, []Actions) -> NewState, Error
  Process(job) -> updatedJob, intent, error


Constructor (creates jobs, coordinates worker, manages Construction API Flow)
  Helper (broadcastStorage, keyStorage, flowStorage)
    ConstructionAPIFlow (-Submit)
    Broadcast()
    Sign()
    JobsProcessing() -> Count
    JobsReady() []jobs
  Handler
    AddressCreated
    TransactionCreated

  Loop:
    var job
    var intent
    for [
      ready jobs...,
      (new jobs excluding create_account and request_funds as long as concurrency lower than required)plans...,
      request funds (if no broadcasting jobs and broadcast completed hasn't been updated since start)
    ]:
      Worker.Process(Job) -> updatedJob, Intent, error
      if errInsufficientAccounts:
        run "create_account" then try jobs again (as long as not existing create account)
      if errInsufficientFunds, errUnsatisfiable:
        continue
      if err != nil:
        THROW ERROR

      job = updatedJob
      intent = intent
      break

    jobID = JobStorage.Update(job) -> only assign identifier and store once successful at least once/only update if successful processing
    if intent:
      networktransaction, transactionidentifier = CreateTransaction(intent) [existing]
      Broadcast(network transaction, intent, transactionIdentifier, jobID)

  Errors:
    ErrUnsatisfiable -> if some action can't be completed because of lack of resources, but not error
    ErrInsufficientFunds -> if all ready fail + no in progress + creating all new jobs fails (don't try create account and request funds), request funds
    ErrInsufficientAccounts -> means we should create a new account, returned when we don't max out (only some addresses are creatable)
  Methods:
    CreateTransaction(Intent) Broadcast, error
```

### Todos
- [x] Add new `constructor` package to `rosetta-sdk-go`
  - [x] Add support for basic job (processing https://github.com/coinbase/rosetta-sdk-go/pull/104)
  - [x] Add primitives
     - [x] `generate_key` (https://github.com/coinbase/rosetta-sdk-go/pull/104)
     - [x] `save_address` (https://github.com/coinbase/rosetta-sdk-go/pull/109)
     - [x] `derive` (https://github.com/coinbase/rosetta-sdk-go/pull/104)
     - [x] `set_variable` (https://github.com/coinbase/rosetta-sdk-go/pull/104)
     - [x] ~`find_account`~
     - [x] ~`find_coin`~
     - [x] `find_balance` (replaces all other find calls) (https://github.com/coinbase/rosetta-sdk-go/pull/112)
     - [x] `print_message` (https://github.com/coinbase/rosetta-sdk-go/pull/109)
     - [x] ~`wait_for_funds`~ (just use `find_account` with a "wait")
     - [x] `math` (https://github.com/coinbase/rosetta-sdk-go/pull/109)
     - [x] `random_string` (https://github.com/coinbase/rosetta-sdk-go/pull/109)
  - [x] Implement `coordinator` (https://github.com/coinbase/rosetta-sdk-go/pull/114)
  - [x] make all calls during execution loop transactional + make `BroadcastComplete` accept a dbtx as an arg (like `BlockWorker`) -> https://github.com/coinbase/rosetta-sdk-go/pull/117
- [x] Add `JobStorage` to `rosetta-sdk-go/storage` (https://github.com/coinbase/rosetta-sdk-go/pull/118)
   - [x] allow for viewing the number of completed jobs of a certain workflow (considered an end condition) -> https://github.com/coinbase/rosetta-sdk-go/pull/118
- [x] replace `rosetta-cli/pkg/constructor` with `rosetta-sdk-go/constructor` (#120) 
- [x] add constructor end conditions (i.e. stop after x transfers) (#122)
  - [x] add bitcoin configuration file example (#122)
- [x] err txn too big (https://github.com/coinbase/rosetta-sdk-go/issues/125)
- [x] populate requested pubkeys (https://github.com/coinbase/rosetta-sdk-go/pull/133)
- [ ] option to return funds to a single address when ending (#119)
  - [ ] could be a reserved workflow ("shutdown") that is called after end condition is met (instead of just halting)
- [x] (Post-Release) Allow for re-processing based on the result from `SuggestedFee` (https://github.com/coinbase/rosetta-sdk-go/pull/144)
     - [x] add a method to the worker that allows for "dry running" a preprocess + metadata to get the suggested fee...this can then be injected into the state for later construction
     - [x] allow for saving certain currencies from suggested fee as variables, then rewriting operations (triggers a re-run of construction flow)
     - [x] if suggested fee is too high, allow for aborting (account may not have enough amount)
     - [x] allow for a fee tolerance to continue (i.e. if fee within X range of Y, continue)
