### ISSUE TITLE
Automated Construction API Testing

### ISSUE THREAD

**Issue by patrick-ogrady** [coinbase/rosetta-cli#68]
Automatically test any Construction API implementation (the equivalent of the `check` command for the Data API).

- [x] Add KeyStorage Backend (https://github.com/coinbase/rosetta-cli/pull/67)
- [x] Add intent parsing support (https://github.com/coinbase/rosetta-sdk-go/pull/78)
- [x] Add scenario parser to `/internal`(#69)
- [x] Support loading `check:construction` settings and scenarios from config file + cleanup commands (#70)
- [x] `StatefulSyncer` refactor (#74)
- [x] Get transaction depth (when first seen)...useful for confirming txs in Construction API (#76)
- [x] `CoinStorage` stateful UTXO coin tracking as `BalanceWorker` (#77)
- [x] Modify parser to assert successful intent [useful for confirming on-chain] (https://github.com/coinbase/rosetta-sdk-go/pull/83)
- [x] Confirm `Operation` in `CoinStorage` was successful before modifying store (#78)
- [x] Cleanup configuration options + default timeout (#79)
- [x] Add `BroadcastStorage` for tracking transaction broadcast, address locking, and confirming transactions at certain depth (calls handler + unlocks address) (#80)
  - block more broadcasts until synced tip == `current_block_identifier` (on restart)
- [ ] Construction API tester (confirmation depth config parameter) (#81 )
  - allow change address for UTXO (so can get more addresses testing at once...could just reuse sender eventhough not supposed to)
  - this also checks if all operations in intent were successful on-chain (modify rosetta-sdk-go/parser to allow for specifying success must be confirmed -> https://github.com/coinbase/rosetta-sdk-go/pull/83)
